### ISSUE TITLE
Exit status 1

### ISSUE THREAD

**Issue by karneaud** [revengecreative/pug-sass-starter-kit#2]
is there any way to prevent the scaffolding from "Exiting" on sass/ js errors? 

>home/vagrant/Code/twin-isle/gulpfile.babel.js:70
>       undefined.emit('end');
>                ^
> TypeError: Cannot read property 'emit' of undefined

**Comment by davidepalazzo** [comment]
Hey @karneaud,

The problem is in `errorHandler` function. When I refactored the code I should have left this as a normal function  and not making it an arrow function. Gulp needs the keyword `this` to invoke `.emit`.

Use a traditional function and gulp watch should stay running even when you have errors on your code.

```js
errorHandler: function(error) {
  console.log(error.message);
  this.emit('end');
}
```

**Comment by karneaud** [comment]
Yeah figured as much once i started diving into the problem.
